name: Deploy

on: 
  push:
    branches:
      - master

jobs:
  deploy_to_live:
    name: Deploy prod hosting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Angular Cli
        run: npm install -g @angular/cli@latest
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Install dependencies
        run: npm install --force
      - name: Run build
        env: 
          SOME_SECRET_KEY: ${{ secrets.SOME_SECRET_KEY }}
        run: ng build
      - name: Firebase use
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase use ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
      - name: Run deploy
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting
